language: php
dist: xenial
php:
- '7.0'
- '7.1'
- '7.2'
- '7.3'
- '7.4'
services:
- docker
script:
- if [ $(phpenv version-name) = "7.0" ]; then docker build -t php-base . -f Dockerfile-70; fi
- if [ $(phpenv version-name) = "7.1" ]; then docker build -t php-base . -f Dockerfile-71; fi
- if [ $(phpenv version-name) = "7.2" ]; then docker build -t php-base . -f Dockerfile-72; fi
- if [ $(phpenv version-name) = "7.3" ]; then docker build -t php-base . -f Dockerfile-73; fi
- if [ $(phpenv version-name) = "7.4" ]; then docker build -t php-base . -f Dockerfile-74; fi
