FROM php:8.3.0alpha1-alpine3.17
MAINTAINER eiriksm <eirik@morland.no>

ENV COMPOSER_DISCARD_CHANGES=1
ENV COMPOSER_MEMORY_LIMIT=-1
ENV COMPOSER_ALLOW_SUPERUSER=1
ENV COMPOSER_PROCESS_TIMEOUT=1200
ENV DRUPAL_CONTRIB_SA_PATH=/root/drupal-contrib-sa

ENV PHP_VERSION=8.3

COPY ./php-install.sh /root/
COPY php-base.ini /usr/local/etc/php/conf.d/

RUN /bin/sh /root/php-install.sh
