shared: &shared
  docker:
    - image: alpine
  steps:
    - checkout
    - setup_remote_docker:
        version: 20.10.7
    - run:
        name: Install Docker client
        command: apk add --no-cache docker
    - run: docker build -t php-base . -f Dockerfile-$PHP_VERSION

jobs:
  "php70":
    environment:
      PHP_VERSION: 70
      COMPOSER_VERSION: 1
    <<: *shared
  "php71":
    environment:
      PHP_VERSION: 71
    <<: *shared
  "php72":
    environment:
      PHP_VERSION: 72
    <<: *shared
  "php73":
    environment:
      PHP_VERSION: 73
    <<: *shared
  "php74":
    environment:
      PHP_VERSION: 74
    <<: *shared
  "php80":
    environment:
      PHP_VERSION: 80
    <<: *shared
  "php81":
    environment:
      PHP_VERSION: 81
    <<: *shared

workflows:
  version: 2
  build:
    jobs:
      - "php70"
      - "php71"
      - "php72"
      - "php73"
      - "php74"
      - "php80"
      - "php81"
