shared: &shared
  steps:
    - checkout
    - setup_remote_docker:
        version: 19.03.13
    - run:
        name: Install Docker client
        command: if [ $PHP_VERSION != "70" ]; then apk add --no-cache docker-cli; fi
    - run:
        name: Install Docker client
        command: if [ $PHP_VERSION = "70" ]; then apk add --no-cache docker; fi
    - run: docker build -t php-base . -f Dockerfile-$PHP_VERSION

jobs:
  "php70":
    environment:
      PHP_VERSION: 70
      COMPOSER_VERSION: 1
    docker:
      - image: ubuntu
    <<: *shared
  "php71":
    environment:
      PHP_VERSION: 71
    docker:
      - image: ubuntu
    <<: *shared
  "php72":
    environment:
      PHP_VERSION: 72
    docker:
      - image: ubuntu
    <<: *shared
  "php73":
    environment:
      PHP_VERSION: 73
    docker:
      - image: ubuntu
    <<: *shared
  "php74":
    environment:
      PHP_VERSION: 74
    docker:
      - image: ubuntu
    <<: *shared
  "php80":
    environment:
      PHP_VERSION: 80
    docker:
      - image: ubuntu
    <<: *shared

workflows:
  version: 2
  build:
    jobs:
      - "php70"
      - "php71"
      - "php72"
      - "php73"
      - "php74"
      - "php80"
