name: Test
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
    steps:
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build test image
        run: docker build -t php-base --build-arg PHP_VERSION=$PHP_VERSION .
        env:
          PHP_VERSION: ${{ matrix.php-version }}

      - name: Output modules 
        run: docker run php-base php -m

      - run: |
          num=$(docker run php-base php -r "print null;" | awk 'END {print NR}')
          # if this prints a line or 2 that can be warnings and what not. don't want those.
          if [ $num != "0" ]
          then
            exit 1
          fi

      - name: Check requirements
        run: docker run -w "/test" -v $(pwd):/test php-base composer install
